markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

baseurl: https://grahammcallister.github.io/mahapps.github.com/

gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jemoji
